stages:
  - build
  - test

.base-build:
  stage: build
  timeout: 8h
  needs:
    pipeline: $PARENT_PIPELINE_ID
    job: pipeline-configure
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./uenv-pipeline/stage-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/uenv-build $SPACK_DEVELOP -m $STACK_MOUNT -u $STACK_UARCH $NO_BWRAP
  after_script:
  - rm -Rf /dev/shm/uenv-build

.base-test:
  stage: test
  timeout: 8h
  needs:
    pipeline: $PARENT_PIPELINE_ID
    job: pipeline-configure
  variables:
    SLURM_TIMELIMIT: 180
    GIT_STRATEGY: fetch
  script:
  - ./uenv-pipeline/stage-test -n $STACK_NAME -s $STACK_SYSTEM -m $STACK_MOUNT -u $STACK_UARCH

{% for job in jobs %}

.build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-build
{% if job.runner.f7t %}
  tags: ["f7t-runner"]
{% else %}
  tags: ["{{job.runner.slurm_runner}}"]
{% endif %}
  variables:
    STACK_MOUNT:      "{{job.mount}}"
    SPACK_DEVELOP:    "{{job.spack_develop}}"
    NO_BWRAP:         "{{job.no_bwrap}}"
    STACK_NAME:       "{{job.uenv}}/{{job.version}}"
    STACK_SYSTEM:     "{{job.system}}"
    STACK_RECIPE:     "{{job.recipe_path}}"
    STACK_UARCH:      "{{job.uarch}}"
    SLURM_PARTITION:  "{{job.partition}}"
    {% for name, value in job.runner.variables.items() %}
    {{ name }}: "{{ value }}"
    {% endfor %}

test-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-test
{% if job.runner.f7t %}
  tags: ["f7t-runner"]
{% else %}
  tags: ["{{job.runner.slurm_runner}}"]
{% endif %}
  # needs: ["build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}"]
  variables:
    STACK_NAME:       "{{job.uenv}}/{{job.version}}"
    STACK_SYSTEM:     "{{job.system}}"
    STACK_UARCH:      "{{job.uarch}}"
    STACK_MOUNT:      "{{job.mount}}"
    SLURM_PARTITION:  "{{job.partition}}"
    {% for name, value in job.runner.variables.items() %}
    {{ name }}: "{{ value }}"
    {% endfor %}

{% endfor %}



{% for job in jobs %}
#@@cmd@@STACK_NAME="{{job.uenv}}/{{job.version}}"
#@@cmd@@STACK_SYSTEM="{{job.system}}"
#@@cmd@@STACK_RECIPE="{{job.recipe_path}}"
#@@cmd@@SPACK_DEVELOP="{{job.spack_develop}}"
#@@cmd@@STACK_MOUNT="{{job.mount}}"
#@@cmd@@STACK_UARCH="{{job.uarch}}"
#@@cmd@@NO_BWRAP="{{job.no_bwrap}}"
#@@cmd@@./uenv-pipeline/stage-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/uenv-build $SPACK_DEVELOP -m $STACK_MOUNT -u $STACK_UARCH $NO_BWRAP ${TESTRUN}
{% endfor %}
