#!/usr/bin/env bash

get_arch() {
  case "$(uname -m)" in
    aarch64)
      echo "arm64"
      ;;
    *)
      echo "amd64"
      ;;
  esac
}

# path where downloaded executables are saved
tool_bin_path=`mktemp -d`
export PATH="$tool_bin_path:$PATH"

###################################################################################
# set up uv
#
# see https://astral.sh/uv/install.sh
###################################################################################

uv_url=https://astral.sh/uv/install.sh

log "download and install uv $uv_url"

curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="$tool_bin_path" sh &> uvlog

log "$(uv --version) installed in ${tool_bin_path}"

###################################################################################
# set up yq
#
# download pre-built executable artifact from
# https://github.com/mikefarah/yq/releases
###################################################################################

yq_url_root=https://github.com/mikefarah/yq/releases/download/v4.45.4/yq_linux_
yq_arch=$(get_arch)
yq_url=${yq_url_root}${yq_arch}
yq_exe=${tool_bin_path}/yq

log "download and install yq $yq_url"

wget --quiet ${yq_url} -O ${yq_exe}
chmod +x ${yq_exe}

log "yq installed as $yq_exe"

############################
## set up oras
############################

oras_arch=$(get_arch)
oras_version=1.1.0
oras_file=oras_${oras_version}_linux_${oras_arch}.tar.gz
oras_url=https://github.com/oras-project/oras/releases/download/v${oras_version}/${oras_file}

log "download and install oras $oras_url"

(cd "$tool_bin_path"; wget --quiet "$oras_url"; tar -xzf $oras_file; rm *.tar.gz)

log "oras v${oras_version} installed in ${tool_bin_path}"

